name: rropen/cscdm
resources:
    cscdm_record:
        subCategory: ""
        name: cscdm_record
        title: cscdm_record Resource - cscdm
        examples:
            - name: www_example_com
              manifest: |-
                {
                  "key": "www",
                  "ttl": 300,
                  "type": "A",
                  "value": "127.0.0.1",
                  "zone": "example.com"
                }
        argumentDocs:
            id: (String) The ID of this resource.
            key: (String)
            last_updated: (String)
            priority: (Number)
            status: (String)
            ttl: (Number)
            type: (String)
            value: (String)
            zone: (String)
        importStatements: []
